#!/usr/bin/env python3
"""
gen-current-pointer.py — regenerate docs/plans/CURRENT.md, the one stable pointer at the live
top-down proof-sketch file (CLAUDE.md router / Rule 9).

THE PROBLEM THIS SOLVES: the sketch is superseded-by-dated-file (a new `vNN` each session/wave close;
old versions stay intact for line citations — CLAUDE.md router). Every doc that names the sketch
(HANDOFF.md, CLAUDE.md's router line, ...) used to hard-code the version number and went stale the
moment a new one landed. `docs/plans/CURRENT.md` is the one generated indirection point: point prose
at it once, and only this generator (not every doc) needs to know how "latest" is computed.

SELECTION RULE: the lexicographically-latest filename matching `docs/plans/*top-down-proof-sketch*.md`
(plain string max — NOT numeric-aware version sort). This matches the file-naming convention in use
(a `YYYY-MM-DD` date prefix dominates the comparison; `vNN` ties within a date sort correctly for the
single-digit-vs-double-digit case only because later dates never coexist with an unresolved tie —
see the docstring note in the tests directory if this is ever revisited).

OUTPUT (docs/plans/CURRENT.md), exactly:
  1. a 2-line generated-file warning comment
  2. the current sketch filename as a markdown link
  3. one context line extracted from the sketch's `# Top-down proof sketch ...` title line

CLI:
  python3 scripts/gen-current-pointer.py            # regenerate docs/plans/CURRENT.md
  python3 scripts/gen-current-pointer.py --check     # exit nonzero if CURRENT.md is stale (for check-all.sh)
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PLANS = ROOT / "docs" / "plans"
CURRENT = PLANS / "CURRENT.md"
GLOB = "*top-down-proof-sketch*.md"

TITLE_RE = re.compile(r"^#\s+(.*\S)\s*$")


def find_latest(plans_dir=PLANS):
    """The lexicographically-latest docs/plans/*top-down-proof-sketch*.md filename (plain string max)."""
    candidates = [p.name for p in plans_dir.glob(GLOB) if p.name != CURRENT.name]
    if not candidates:
        raise SystemExit(f"gen-current-pointer: no files matching {GLOB} in {plans_dir}")
    return max(candidates)


def extract_context_line(sketch_path):
    """The sketch's title line (the first `# ...` heading), stripped of the leading `# `."""
    with open(sketch_path, encoding="utf-8") as f:
        for line in f:
            m = TITLE_RE.match(line)
            if m:
                return m.group(1)
    raise SystemExit(f"gen-current-pointer: no '# ' title line found in {sketch_path}")


def render(latest_name, context_line):
    return (
        "<!-- GENERATED by scripts/gen-current-pointer.py — do not hand-edit; re-run it after adding a "
        "new dated sketch file. -->\n"
        "<!-- Points at the lexicographically-latest docs/plans/*top-down-proof-sketch*.md (CLAUDE.md "
        "router / Rule 9). -->\n"
        "\n"
        f"[{latest_name}]({latest_name})\n"
        "\n"
        f"{context_line}\n"
    )


def main(argv):
    check = "--check" in argv
    latest_name = find_latest()
    context_line = extract_context_line(PLANS / latest_name)
    rendered = render(latest_name, context_line)

    if check:
        if not CURRENT.exists():
            print("gen-current-pointer --check: docs/plans/CURRENT.md does not exist", file=sys.stderr)
            return 1
        existing = CURRENT.read_text(encoding="utf-8")
        if existing != rendered:
            print(
                "gen-current-pointer --check: docs/plans/CURRENT.md is STALE — "
                "re-run `python3 scripts/gen-current-pointer.py`",
                file=sys.stderr,
            )
            return 1
        print(f"gen-current-pointer --check: OK ({latest_name})")
        return 0

    CURRENT.write_text(rendered, encoding="utf-8")
    print(f"gen-current-pointer: wrote {CURRENT.relative_to(ROOT)} -> {latest_name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
