#!/usr/bin/env python3
r"""
gen-report-stats.py — the CAMPAIGN-STATISTICS generated layer of the lab-book.

WHAT IT PRODUCES (all under report/generated/stats/, all generated — never hand-edit):
  campaign-extract.json  the committed DATA SNAPSHOT (the only input to rendering)
  preamble.tex           packages + the Okabe-Ito palette + pgfplots setup (\input from main.tex)
  headline.tex           the frontmatter headline block (\input right after \maketitle)
  body.tex               the section body: subsections, tables, pgfplots charts, colophon

THE STALENESS PROBLEM AND ITS SOLUTION (read this before changing anything).
  Statistics about a repo are derived from things that change on EVERY commit (git history, the
  fr controller log, the af ledgers). A naive byte-freshness gate over such a generator would be
  permanently red: the commit that lands the regenerated tables itself changes the inputs.
  So the generator is split in two, with a committed snapshot between the halves:

      EXTRACT  (explicit, human-run)   sources -> report/generated/stats/campaign-extract.json
      RENDER   (deterministic, gated)  campaign-extract.json -> *.tex

  Only RENDER is gated. `--check` re-renders from the COMMITTED extract and compares bytes, so it
  is stable across ordinary commits and fails exactly when it should: someone hand-edited a
  generated .tex, or changed the renderer without re-rendering. Refreshing the numbers is a
  deliberate act (`--extract`), documented in the section's own colophon, and the extract records
  its own `extracted_at` so the rendered section always states the as-of date in the open.

  `--check` additionally prints a non-fatal DRIFT ADVISORY comparing a handful of cheap live counts
  against the snapshot, so a badly stale snapshot is visible without being a commit-blocker.

PROGENITOR DATA (../almost-idempotent-positive-maps). Mined live during `--extract` when the sibling
  repo is present; when it is absent the previously committed progenitor block is carried forward
  unchanged (and flagged `carried_forward: true`). RENDER never touches the sibling, so the gate is
  green on machines that do not have it.

HONESTY. Every number here is a count of an artifact that exists in the repos. Nothing is modelled,
  extrapolated, or estimated unless the field name says so and the rendered text says so. LLM token
  consumption is NOT recoverable from the record; the section says so explicitly rather than
  inventing a figure.

Usage:
  python3 scripts/gen-report-stats.py --extract      # refresh the snapshot from live sources, then render
  python3 scripts/gen-report-stats.py                # render from the committed snapshot
  python3 scripts/gen-report-stats.py --check        # gate: re-render, byte-compare, drift advisory
"""

import collections
import datetime as _dt
import json
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "report" / "generated" / "stats"
EXTRACT = OUT_DIR / "campaign-extract.json"
PROGENITOR_NAME = "almost-idempotent-positive-maps"


def _find_sibling():
    """Locate ../almost-idempotent-positive-maps, tolerating a git worktree checkout.

    In a linked worktree ROOT.parent is the worktrees scratch dir, not the projects dir, so we also
    resolve the MAIN working tree through .git and look beside that. `AISM_PROGENITOR` overrides.
    """
    env = os.environ.get("AISM_PROGENITOR")
    cands = [pathlib.Path(env)] if env else []
    cands.append(ROOT.parent / PROGENITOR_NAME)
    dotgit = ROOT / ".git"
    if dotgit.is_file():                       # linked worktree: ".git" is a gitdir pointer file
        m = re.match(r"gitdir:\s*(.+)", dotgit.read_text(encoding="utf-8", errors="replace").strip())
        if m:
            p = pathlib.Path(m.group(1).strip())
            for parent in p.parents:           # .../<main>/.git/worktrees/<name> -> <main>
                if parent.name == ".git":
                    cands.append(parent.parent.parent / PROGENITOR_NAME)
                    break
    for c in cands:
        if c.is_dir():
            return c
    return cands[-1]


SIBLING = _find_sibling()

GENERATED_TEX = ("preamble.tex", "headline.tex", "body.tex")

# Okabe-Ito colourblind-safe qualitative palette (same eight colours the DAG atlas uses).
OKABE_ITO = [
    ("oiOrange", "E69F00"),
    ("oiSky", "56B4E9"),
    ("oiGreen", "009E73"),
    ("oiYellow", "F0E442"),
    ("oiBlue", "0072B2"),
    ("oiVermillion", "D55E00"),
    ("oiPurple", "CC79A7"),
    ("oiBlack", "000000"),
]

BANNER = "% GENERATED by scripts/gen-report-stats.py — DO NOT EDIT BY HAND.\n"


# ===================================================================== helpers

def _read(path, default=""):
    try:
        return pathlib.Path(path).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return default


def _frontmatter_field(text, field):
    m = re.search(r"^%s:\s*(.*)$" % re.escape(field), text, re.M)
    return m.group(1).strip() if m else None


def _day(ts):
    """ISO timestamp (or date) -> YYYY-MM-DD."""
    return (ts or "")[:10] or None


def _git(repo, *args):
    try:
        out = subprocess.run(["git", "-C", str(repo)] + list(args),
                             capture_output=True, text=True, check=True, timeout=120)
    except (OSError, subprocess.SubprocessError):
        return None
    return out.stdout


def _counter(items):
    """Deterministic dict from a Counter: sorted by descending count, then key."""
    c = collections.Counter(items)
    return dict(sorted(c.items(), key=lambda kv: (-kv[1], str(kv[0]))))


def _listdir(path, suffix=None, exclude=()):
    p = pathlib.Path(path)
    if not p.is_dir():
        return []
    out = []
    for name in sorted(os.listdir(p)):
        if name in exclude:
            continue
        if suffix and not name.endswith(suffix):
            continue
        out.append(name)
    return out


# ===================================================================== extract

def extract_git(repo):
    """Commit calendar + author + subject taxonomy. Snapshotted (git history is volatile)."""
    log = _git(repo, "log", "--format=%ad\x1f%an\x1f%s", "--date=short")
    if log is None:
        return None
    per_day = collections.Counter()
    authors = collections.Counter()
    subjects = collections.Counter()
    n = 0
    for line in log.splitlines():
        if not line.strip():
            continue
        parts = line.split("\x1f")
        if len(parts) != 3:
            continue
        date, author, subject = parts
        n += 1
        per_day[date] += 1
        authors[author] += 1
        # taxonomy: the token before the first ':' (the repo's de-facto commit prefix convention)
        head = subject.split(":", 1)[0].strip() if ":" in subject else subject.strip()
        subjects[head] += 1
    days = sorted(per_day)
    return {
        "commits": n,
        "first_day": days[0] if days else None,
        "last_day": days[-1] if days else None,
        "active_days": len(days),
        "per_day": {d: per_day[d] for d in days},
        "authors": _counter(authors.elements()),
        "subject_prefixes": dict(sorted(subjects.items(), key=lambda kv: (-kv[1], kv[0]))[:14]),
    }


def extract_frontier(repo):
    """The fr controller log: cycles, arms, outcomes, worker mix, decisions, evidence tiers."""
    path = pathlib.Path(repo) / ".frontier" / "log.jsonl"
    if not path.is_file():
        return None
    recs = []
    for line in _read(path).splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            recs.append(json.loads(line))
        except ValueError:
            continue
    per_day = collections.Counter()
    outcomes = collections.Counter()
    arms = collections.Counter()
    arm_outcome = collections.defaultdict(collections.Counter)
    arm_span = {}
    workers = collections.Counter()
    models = collections.Counter()
    roles = collections.Counter()
    decisions = collections.Counter()
    tiers = collections.Counter()
    classes = collections.Counter()
    banked_days = collections.Counter()
    for r in recs:
        ts = r.get("ts") or ""
        d = _day(ts)
        if d:
            per_day[d] += 1
        oc = r.get("outcome") or "unrecorded"
        outcomes[oc] += 1
        arm = r.get("arm")
        if arm:
            arms[arm] += 1
            arm_outcome[arm][oc] += 1
            lo, hi = arm_span.get(arm, (ts, ts))
            arm_span[arm] = (min(lo, ts), max(hi, ts))
        for w in (r.get("workers") or []):
            m = (w or {}).get("model") or "?"
            ro = (w or {}).get("role") or "?"
            workers["%s / %s" % (m, ro)] += 1
            models[m] += 1
            roles[ro] += 1
        dec = (r.get("decision") or {}).get("type")
        if dec:
            decisions[dec] += 1
        ev = r.get("evidence")
        if isinstance(ev, dict):
            if ev.get("tier"):
                tiers[ev["tier"]] += 1
            if ev.get("class"):
                classes[ev["class"]] += 1
        if oc == "banked" and d:
            banked_days[d] += 1
    cycles = [r.get("cycle") for r in recs if isinstance(r.get("cycle"), int)]
    days = sorted(per_day)
    return {
        "records": len(recs),
        "max_cycle": max(cycles) if cycles else None,
        "first_ts": min((r.get("ts") or "" for r in recs), default=None),
        "last_ts": max((r.get("ts") or "" for r in recs), default=None),
        "active_days": len(days),
        "per_day": {d: per_day[d] for d in days},
        "banked_per_day": dict(sorted(banked_days.items())),
        "outcomes": _counter(outcomes.elements()),
        "arms": _counter(arms.elements()),
        "arm_outcomes": {a: _counter(arm_outcome[a].elements()) for a in sorted(arm_outcome)},
        "arm_span": {a: {"first": arm_span[a][0], "last": arm_span[a][1]} for a in sorted(arm_span)},
        "workers": _counter(workers.elements()),
        "worker_jobs": int(sum(workers.values())),
        "worker_models": _counter(models.elements()),
        "worker_roles": _counter(roles.elements()),
        "decisions": _counter(decisions.elements()),
        "evidence_tiers": _counter(tiers.elements()),
        "evidence_classes": _counter(classes.elements()),
    }


def extract_portfolio(repo):
    path = pathlib.Path(repo) / ".frontier" / "portfolio.json"
    if not path.is_file():
        return None
    try:
        p = json.loads(_read(path))
    except ValueError:
        return None
    arms = []
    for a in (p.get("arms") or []):
        arms.append({
            "id": a.get("id"),
            "priority": a.get("priority"),
            "desc": (a.get("desc") or "").strip(),
        })
    return {"arms": arms, "goal": (p.get("goal") or "").strip(),
            "frontier": (p.get("frontier") or "").strip() if isinstance(p.get("frontier"), str) else None,
            "verdict_files": len(_listdir(pathlib.Path(repo) / ".frontier" / "verdicts"))}


def extract_af(repo):
    """Per-workspace af metrics from the append-only ledgers (the elevation record)."""
    proofs = pathlib.Path(repo) / "proofs"
    if not proofs.is_dir():
        return None
    per_ws = []
    totals = collections.Counter()
    owner_roles = collections.Counter()
    for name in sorted(os.listdir(proofs)):
        ledger = proofs / name / "ledger"
        if not ledger.is_dir():
            continue
        entries = []
        for fn in sorted(os.listdir(ledger)):
            if not fn.endswith(".json"):
                continue
            try:
                entries.append(json.loads(_read(ledger / fn)))
            except ValueError:
                continue
        if not entries:
            continue
        c = collections.Counter()
        rounds = set()
        root_validated = None
        times = []
        for e in entries:
            t = e.get("type") or "?"
            c[t] += 1
            totals[t] += 1
            if e.get("timestamp"):
                times.append(e["timestamp"])
            if t == "node_validated" and e.get("node_id") == "1":
                root_validated = e.get("timestamp")
            if t == "nodes_claimed":
                owner = e.get("owner") or ""
                m = re.search(r"-r(\d+)$", owner)
                if m:
                    rounds.add(int(m.group(1)))
                if owner.startswith("v-"):
                    owner_roles["verifier"] += 1
                elif owner.startswith("pf-"):
                    owner_roles["prover (fix round)"] += 1
                elif owner.startswith("prover-build"):
                    owner_roles["prover (initial build)"] += 1
                else:
                    owner_roles["other"] += 1
        per_ws.append({
            "id": name,
            "ledger_entries": len(entries),
            "nodes": c.get("node_created", 0),
            "validated": c.get("node_validated", 0),
            "archived": c.get("node_archived", 0),
            "challenges": c.get("challenge_raised", 0),
            "challenges_resolved": c.get("challenge_resolved", 0),
            "amendments": c.get("node_amended", 0),
            "defs_imported": c.get("def_added", 0),
            "claims": c.get("nodes_claimed", 0),
            "max_round": max(rounds) if rounds else 0,
            "root_validated": root_validated,
            "first_ts": min(times) if times else None,
            "last_ts": max(times) if times else None,
        })
    validated = [w for w in per_ws if w["root_validated"]]
    return {
        "workspaces": len(per_ws),
        "root_validated": len(validated),
        "seeded_not_validated": len(per_ws) - len(validated),
        "ledger_entries": int(sum(w["ledger_entries"] for w in per_ws)),
        "entry_types": dict(sorted(totals.items(), key=lambda kv: (-kv[1], kv[0]))),
        "owner_roles": _counter(owner_roles.elements()),
        "nodes_total": int(sum(w["nodes"] for w in per_ws)),
        "challenges_total": int(sum(w["challenges"] for w in per_ws)),
        "amendments_total": int(sum(w["amendments"] for w in per_ws)),
        "workspaces_detail": per_ws,
        "validation_days": dict(sorted(collections.Counter(
            _day(w["root_validated"]) for w in validated).items())),
    }


def extract_registry(repo):
    d = pathlib.Path(repo) / "argument" / "lemmas"
    if not d.is_dir():
        return None
    status = collections.Counter()
    af = collections.Counter()
    kind = collections.Counter()
    n = 0
    for name in sorted(os.listdir(d)):
        if not name.endswith(".md"):
            continue
        t = _read(d / name)
        n += 1
        status[_frontmatter_field(t, "status") or "unset"] += 1
        af[_frontmatter_field(t, "af") or "none"] += 1
        kind[_frontmatter_field(t, "kind") or "unset"] += 1
    return {"results": n,
            "status": _counter(status.elements()),
            "af": _counter(af.elements()),
            "kind": _counter(kind.elements())}


def extract_definitions(repo):
    d = pathlib.Path(repo) / "definitions"
    if not d.is_dir():
        return None
    kind = collections.Counter()
    status = collections.Counter()
    n = 0
    for name in sorted(os.listdir(d)):
        if not name.endswith(".md") or name in ("README.md", "INDEX.md"):
            continue
        t = _read(d / name)
        n += 1
        kind[_frontmatter_field(t, "kind") or "unset"] += 1
        status[_frontmatter_field(t, "status") or "unset"] += 1
    return {"definitions": n, "kind": _counter(kind.elements()), "status": _counter(status.elements())}


def extract_runs(repo):
    d = pathlib.Path(repo) / "runs"
    if not d.is_dir():
        return None
    bundles = [n for n in sorted(os.listdir(d)) if (d / n).is_dir()]
    per_month = collections.Counter()
    scripts = 0
    for b in bundles:
        m = re.match(r"(\d{4}-\d{2})-\d{2}-", b)
        if m:
            per_month[m.group(1)] += 1
        sd = d / b / "scripts"
        if sd.is_dir():
            scripts += len([f for f in os.listdir(sd) if f.endswith(".py")])
    return {"bundles": len(bundles), "per_month": dict(sorted(per_month.items())),
            "bundle_scripts": scripts, "ids": bundles}


def extract_docs(repo):
    r = pathlib.Path(repo)
    out = {}
    for sub in ("plans", "waves", "audits", "lit-review", "recon", "tooling-feedback", "ingest"):
        p = r / "docs" / sub
        out[sub] = len([n for n in _listdir(p)]) if p.is_dir() else 0
    ingest_exp = r / "docs" / "ingest" / "experiments"
    out["ingest_experiment_files"] = len(_listdir(ingest_exp)) if ingest_exp.is_dir() else 0
    sections = r / "report" / "sections"
    shards = _listdir(sections, suffix=".tex")
    lines = sum(len(_read(sections / s).splitlines()) for s in shards)
    out["report_shards"] = len(shards)
    out["report_shard_lines"] = lines
    return out


def extract_findings(repo):
    """The dead-route / gotcha census, read off FINDINGS.md's hand-built mechanism index."""
    t = _read(pathlib.Path(repo) / "FINDINGS.md")
    if not t:
        return None
    tags = {}
    for m in re.finditer(r"^\*\*([A-Z][A-Z-]+)\*\*[^:]*?:(.+)$", t, re.M):
        tag, body = m.group(1), m.group(2)
        tags[tag] = len(re.findall(r"\[[^\]]+\]\(#", body))
    learn = _read(pathlib.Path(repo) / "docs" / "LEARNINGS.md")
    return {
        "dated_entries": len(re.findall(r"^## \d{4}-", t, re.M)),
        "mechanism_tags": dict(sorted(tags.items())),
        "stop_markers": t.count("\u26d4"),
        "retractions": len(re.findall(r"^## \d{4}-", learn, re.M)) if learn else 0,
    }


def extract_worklog(repo):
    t = _read(pathlib.Path(repo) / "docs" / "worklog.md")
    if not t:
        return None
    heads = re.findall(r"^## (.+)$", t, re.M)
    sessions = set()
    for h in heads:
        for m in re.finditer(r"[Ss]ession (\d+)", h):
            sessions.add(int(m.group(1)))
    days = sorted({m.group(0) for m in re.finditer(r"\d{4}-\d{2}-\d{2}", t)})
    waves = {int(m.group(1)) for m in re.finditer(r"\bW(\d+)\b", t)}
    return {"entries": len(heads),
            "sessions_named": len(sessions),
            "max_session": max(sessions) if sessions else None,
            "wave_labels": len(waves),
            "max_wave": max(waves) if waves else None,
            "first_date": days[0] if days else None,
            "last_date": days[-1] if days else None,
            "lines": len(t.splitlines())}


def extract_beads(repo):
    p = pathlib.Path(repo) / ".beads" / "issues.jsonl"
    if not p.is_file():
        return None
    issues, memories = [], 0
    for line in _read(p).splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            r = json.loads(line)
        except ValueError:
            continue
        if r.get("_type") == "memory":
            memories += 1
        else:
            issues.append(r)
    status = collections.Counter(r.get("status") or "unset" for r in issues)
    itype = collections.Counter(r.get("issue_type") or "unset" for r in issues)
    prio = collections.Counter(str(r.get("priority")) for r in issues)
    created = collections.Counter(_day(r.get("created_at")) for r in issues if r.get("created_at"))
    closed = collections.Counter(_day(r.get("closed_at")) for r in issues if r.get("closed_at"))
    return {"issues": len(issues), "memories": memories,
            "status": _counter(status.elements()), "type": _counter(itype.elements()),
            "priority": _counter(prio.elements()),
            "created_per_day": dict(sorted(created.items())),
            "closed_per_day": dict(sorted(closed.items()))}


def extract_tooling(repo):
    r = pathlib.Path(repo) / "scripts"
    if not r.is_dir():
        return None
    gate_lines = 0
    gates = 0
    total_lines = 0
    files = 0
    for dirpath, _dirnames, filenames in os.walk(r):
        for fn in sorted(filenames):
            if not (fn.endswith(".py") or fn.endswith(".sh")):
                continue
            p = pathlib.Path(dirpath) / fn
            n = len(_read(p).splitlines())
            total_lines += n
            files += 1
            if fn.startswith("check-") or fn == "argument.py":
                gates += 1
                gate_lines += n
    tests = _listdir(r / "tests", suffix=".py")
    return {"script_files": files, "script_lines": total_lines,
            "gate_scripts": gates, "gate_lines": gate_lines,
            "test_files": len(tests),
            "test_lines": sum(len(_read(r / "tests" / t).splitlines()) for t in tests)}


def extract_refs(repo):
    t = _read(pathlib.Path(repo) / "refs" / "manifest" / "SOURCES.md")
    ids = re.findall(r"^\|\s*`([a-z0-9][^`]*)`\s*\|", t, re.M)
    lock = pathlib.Path(repo) / "refs" / "manifest" / "sources.lock.json"
    nfiles = 0
    if lock.is_file():
        try:
            nfiles = len(json.loads(_read(lock)).get("files") or {})
        except ValueError:
            nfiles = 0
    return {"sources": len(ids), "source_ids": ids, "locked_files": nfiles}


def extract_repo(repo, with_git=True):
    repo = pathlib.Path(repo)
    out = {
        "path_name": repo.name,
        "frontier": extract_frontier(repo),
        "portfolio": extract_portfolio(repo),
        "af": extract_af(repo),
        "registry": extract_registry(repo),
        "definitions": extract_definitions(repo),
        "runs": extract_runs(repo),
        "docs": extract_docs(repo),
        "findings": extract_findings(repo),
        "worklog": extract_worklog(repo),
        "beads": extract_beads(repo),
        "tooling": extract_tooling(repo),
        "refs": extract_refs(repo),
    }
    if with_git:
        out["git"] = extract_git(repo)
    return out


def do_extract():
    prev = {}
    if EXTRACT.is_file():
        try:
            prev = json.loads(_read(EXTRACT))
        except ValueError:
            prev = {}
    data = {
        "schema": 1,
        "extracted_at": _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "generator": "scripts/gen-report-stats.py",
        "successor": extract_repo(ROOT),
    }
    if SIBLING.is_dir():
        prog = extract_repo(SIBLING)
        prog["carried_forward"] = False
        prog["mined_at"] = data["extracted_at"]
        data["progenitor"] = prog
    elif prev.get("progenitor"):
        prog = dict(prev["progenitor"])
        prog["carried_forward"] = True
        data["progenitor"] = prog
        sys.stderr.write("[gen-report-stats] sibling repo absent — progenitor block carried forward\n")
    else:
        data["progenitor"] = None
        sys.stderr.write("[gen-report-stats] sibling repo absent and no prior snapshot — "
                         "progenitor block empty\n")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    EXTRACT.write_text(json.dumps(data, indent=1, sort_keys=True, ensure_ascii=False) + "\n",
                       encoding="utf-8")
    return data


# ====================================================================== render

def tex(s):
    """Escape a plain string for LaTeX text mode."""
    if s is None:
        return "--"
    s = str(s)
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
                 ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
                 ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")):
        s = s.replace(a, b)
    return s


def code(s):
    return r"\texttt{%s}" % tex(s)


def code_brk(s):
    r"""\texttt{} with an INVISIBLE break opportunity after every hyphen and slash.

    cmtt has no hyphenation, so a long identifier in prose is an unbreakable box and runs into
    the margin. \discretionary{}{}{} adds a legal break point without printing a hyphen.
    """
    return r"\texttt{%s}" % tex(s).replace("-", r"-\discretionary{}{}{}").replace(
        "/", r"/\discretionary{}{}{}")


def num(n):
    """Thousands-separated integer, LaTeX-safe."""
    if n is None:
        return "--"
    return "{:,}".format(int(n)).replace(",", r"\,")


def pct(a, b):
    return "--" if not b else "%.1f\\%%" % (100.0 * a / b)


def _dnum(day):
    """Days since the campaign origin (progenitor day 0) — the shared chart x-axis."""
    y, m, d = (int(x) for x in day.split("-"))
    return (_dt.date(y, m, d) - CHART_ORIGIN).days


CHART_ORIGIN = _dt.date(2026, 6, 2)


def _origin_from(data):
    days = []
    for side in ("progenitor", "successor"):
        r = (data.get(side) or {})
        g = (r.get("git") or {})
        if g.get("first_day"):
            days.append(g["first_day"])
    return min(days) if days else "2026-06-02"


def render(data):
    """Deterministic: the same extract JSON always yields byte-identical .tex."""
    global CHART_ORIGIN
    o = _origin_from(data)
    CHART_ORIGIN = _dt.date(*(int(x) for x in o.split("-")))
    return {
        "preamble.tex": render_preamble(),
        "headline.tex": render_headline(data),
        "body.tex": render_body(data),
    }


def render_preamble():
    L = [BANNER,
         "% Packages + palette used ONLY by the generated campaign-statistics layer.\n",
         "% \\input from report/main.tex's preamble (one line, documented there).\n",
         "% NOTE: no pdflscape. Every generated table fits the portrait text block, so a rotated",
         "% page would cost readability without buying width; the wide table (the elevation",
         "% ledger) is a portrait longtable that breaks across pages with a repeated header.",
         r"\usepackage{longtable}", "",
         "% `float` + [H]: this section is float-dense, and drifting tables/figures would break the",
         "% narrative order. Every generated float is pinned exactly where the text puts it.",
         r"\usepackage{float}", "",
         r"\usepackage{xcolor}", "", r"\usepackage{pgfplots}", "",
         r"\pgfplotsset{compat=1.16}", "",
         "% cleveref must load AFTER hyperref; this file is \\input at the END of the preamble.",
         "% It is used only by the generated statistics body (\\Cref{...}); no other shard uses it.",
         r"\usepackage[nameinlink]{cleveref}", "",
         "% Okabe--Ito qualitative palette (colourblind-safe); shared with the DAG atlas.",
         ]
    for name, hexv in OKABE_ITO:
        L.append(r"\definecolor{%s}{HTML}{%s}" % (name, hexv))
    L += [
        "",
        r"\pgfplotsset{",
        r"  aismbase/.style={",
        "    % width/height are the TOTAL picture size (no `scale only axis`), so axis labels and",
        "    % rotated ticks stay inside the text block instead of running into the margin.",
        r"    width=\linewidth, height=6.6cm,",
        r"    tick align=outside, tick pos=left,",
        r"    axis line style={draw=black!55}, major grid style={draw=black!12},",
        r"    label style={font=\small}, tick label style={font=\footnotesize},",
        r"    legend style={font=\footnotesize, draw=black!25, fill=white, fill opacity=0.9,"
        r" text opacity=1, cells={anchor=west}},",
        r"    every axis plot/.append style={line width=0.7pt},",
        r"  },",
        r"}",
        "",
    ]
    return "\n".join(L) + "\n"


# ------------------------------------------------------------------ headline

def render_headline(data):
    s = data["successor"]
    p = data.get("progenitor") or {}
    fr = s.get("frontier") or {}
    af = s.get("af") or {}
    reg = s.get("registry") or {}
    sg = s.get("git") or {}
    pg = p.get("git") or {}
    wl = s.get("worklog") or {}
    runs = s.get("runs") or {}
    paf = p.get("af") or {}

    span_days = 0
    if pg.get("first_day") and sg.get("last_day"):
        a = _dt.date(*(int(x) for x in pg["first_day"].split("-")))
        b = _dt.date(*(int(x) for x in sg["last_day"].split("-")))
        span_days = (b - a).days + 1
    elif sg.get("first_day") and sg.get("last_day"):
        a = _dt.date(*(int(x) for x in sg["first_day"].split("-")))
        b = _dt.date(*(int(x) for x in sg["last_day"].split("-")))
        span_days = (b - a).days + 1

    tiles = [
        (num(af.get("root_validated")), r"\texttt{af}-validated results (T0)"),
        (num(reg.get("results")), "registry results"),
        (num(fr.get("max_cycle") or fr.get("records")), r"\texttt{fr} controller cycles"),
        (num(wl.get("entries")), "logged work sessions"),
        (num(span_days), "days, first commit to last"),
        (num((af.get("nodes_total") or 0) + (paf.get("nodes_total") or 0)),
         "adversarial proof nodes"),
    ]

    L = [BANNER,
         "% Frontmatter headline block: \\input immediately after \\maketitle in report/main.tex.",
         "% Numbers come from report/generated/stats/campaign-extract.json (see the colophon in the",
         "% campaign-statistics section for the staleness semantics).",
         r"\begingroup",
         r"\par\addvspace{0.8\baselineskip}",
         r"\noindent\hrulefill\par\nobreak\vspace{0.4ex}",
         r"\begin{center}",
         r"{\footnotesize\scshape The campaign in numbers\quad"
         r"(snapshot %s; see \S\ref{sec:campaign-statistics})}\par\vspace{0.6ex}" %
         tex((data.get("extracted_at") or "")[:10]),
         r"\setlength{\tabcolsep}{6pt}",
         r"\begin{tabular}{@{}%s@{}}" % ("c" * len(tiles)),
         " & ".join(r"{\large\bfseries %s}" % v for v, _ in tiles) + r" \\[0.15ex]",
         " & ".join(r"{\scriptsize %s}" % k for _, k in tiles) + r" \\",
         r"\end{tabular}",
         r"\end{center}",
         r"\vspace{-0.3ex}\noindent\hrulefill\par",
         r"\addvspace{0.8\baselineskip}",
         r"\endgroup",
         ]
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- body parts

def _longtable(colspec, header, rows, caption, label, notes=None, fontsize=None):
    L = ([r"\begingroup%s" % fontsize] if fontsize else []) + [
         r"\setlength{\tabcolsep}{3pt}" if fontsize else r"\relax",
         r"\begin{longtable}{%s}" % colspec,
         r"\caption{%s}\label{%s}\\" % (caption, label),
         r"\toprule", header + r" \\", r"\midrule", r"\endfirsthead",
         r"\multicolumn{%d}{@{}l}{\footnotesize\itshape (\Cref{%s}, continued)}\\" %
         (colspec.count("l") + colspec.count("r") + colspec.count("c"), label),
         r"\toprule", header + r" \\", r"\midrule", r"\endhead",
         r"\midrule", r"\multicolumn{%d}{r@{}}{\footnotesize\itshape (continued)}\\" %
         (colspec.count("l") + colspec.count("r") + colspec.count("c")),
         r"\endfoot", r"\bottomrule", r"\endlastfoot"]
    L += [r + r" \\" for r in rows]
    L.append(r"\end{longtable}")
    if notes:
        L.append(r"\noindent{\footnotesize %s\par}" % notes)
    if fontsize:
        L.append(r"\endgroup")
    return "\n".join(L)


def _table(colspec, header, rows, caption, label, notes=None, star=False):
    env = "table"
    L = [r"\begin{%s}[H]" % env, r"\centering",
         r"\caption{%s}\label{%s}" % (caption, label),
         r"\begin{tabular}{%s}" % colspec, r"\toprule", header + r" \\", r"\midrule"]
    L += [r + r" \\" for r in rows]
    L += [r"\bottomrule", r"\end{tabular}"]
    if notes:
        L.append(r"\par\vspace{0.6ex}{\footnotesize %s}" % notes)
    L.append(r"\end{%s}" % env)
    return "\n".join(L)


def _coords(pairs):
    return " ".join("(%s,%s)" % (a, b) for a, b in pairs)


def sec_headline(data):
    s = data["successor"]
    p = data.get("progenitor") or {}
    sg, pg = s.get("git") or {}, p.get("git") or {}
    fr = s.get("frontier") or {}
    af, paf = s.get("af") or {}, p.get("af") or {}
    reg, preg = s.get("registry") or {}, p.get("registry") or {}
    dfs, pdfs = s.get("definitions") or {}, p.get("definitions") or {}
    wl, pwl = s.get("worklog") or {}, p.get("worklog") or {}

    rows = [
        ("First commit", tex(pg.get("first_day")), tex(sg.get("first_day"))),
        ("Last commit in snapshot", tex(pg.get("last_day")), tex(sg.get("last_day"))),
        ("Commits", num(pg.get("commits")), num(sg.get("commits"))),
        ("Days with a commit", num(pg.get("active_days")), num(sg.get("active_days"))),
        ("Work-log entries", num(pwl.get("entries")), num(wl.get("entries"))),
        (r"\texttt{fr} controller cycles", "--- (no controller)", num(fr.get("max_cycle"))),
        ("Registry results", num(preg.get("results")), num(reg.get("results"))),
        ("Definition shards", num(pdfs.get("definitions")), num(dfs.get("definitions"))),
        (r"\texttt{af} workspaces", num(paf.get("workspaces")), num(af.get("workspaces"))),
        (r"\texttt{af}-validated roots (T0)", num(paf.get("root_validated")), num(af.get("root_validated"))),
        ("Adversarial proof nodes built", num(paf.get("nodes_total")), num(af.get("nodes_total"))),
        ("Ledger entries (append-only)", num(paf.get("ledger_entries")), num(af.get("ledger_entries"))),
        ("Numerical run bundles", num((p.get("runs") or {}).get("bundles")),
         num((s.get("runs") or {}).get("bundles"))),
    ]
    body = [r"\subsection{The campaign at a glance}\label{sec:stats-glance}", "",
            "This section is machine-generated from the two repositories' own records: the "
            r"\texttt{fr} controller log, the append-only \texttt{af} proof ledgers, the registry and "
            "definition shards, the run bundles, the work log, the issue tracker, and the git "
            r"history. \Cref{tab:stats-glance} places the progenitor campaign "
            "(\\texttt{almost-idempotent-positive-maps}, where the classical portfolio was born) "
            "beside this one. Nothing below is a mathematical claim; nothing below promotes any "
            "result up the rigour ladder.", ""]
    body.append(_table(
        "l r r",
        r"Quantity & Progenitor & This repository",
        [" & ".join(r) for r in rows],
        "The two campaigns side by side. The progenitor column is a snapshot of "
        r"\texttt{../almost-idempotent-positive-maps}; that repository has no \texttt{fr} "
        "controller, so its exploration record lives only in its work log and git history.",
        "tab:stats-glance",
        notes="``T0'' is this project's top-of-ladder tag for a result whose "
              r"\texttt{af} proof tree has a \texttt{validated} root under the "
              "fresh-prover/fresh-verifier protocol. It is not a Lean proof."))
    return "\n".join(body)


def sec_method(data):
    s = data["successor"]
    p = data.get("progenitor") or {}
    L = [r"\subsection{What is counted, and what cannot be}\label{sec:stats-method}", "",
         r"\textbf{Counted, exactly.} Every figure in this section is a count of an artifact that "
         "exists in one of the two repositories at the snapshot instant: a JSON record in "
         r"\texttt{.frontier/log.jsonl}, a ledger entry under \texttt{proofs/*/ledger/}, a "
         r"front-matter field in an \texttt{argument/lemmas/*.md} or \texttt{definitions/*.md} "
         r"shard, a directory under \texttt{runs/} or \texttt{docs/}, a heading in "
         r"\texttt{docs/worklog.md} or \texttt{FINDINGS.md}, a record in "
         r"\texttt{.beads/issues.jsonl}, or a commit in \texttt{git log}. No figure is modelled, "
         "interpolated, or extrapolated.", "",
         r"\textbf{Not recoverable: LLM token consumption.} The single most-asked statistic about a "
         "campaign like this one --- how many tokens, and at what cost --- is \\emph{not} present in "
         "the record and is not reconstructed here. Neither repository ever logged token counts, "
         "context sizes, wall-clock durations, or billing data; the "
         r"\texttt{af} ledger records who claimed which node and when, not how much text was "
         "produced to do it, and the \\texttt{fr} log records a worker's "
         r"\texttt{model:role} pair, not its usage. What \emph{is} recoverable is the "
         r"\emph{job} count --- how many distinct prover/verifier invocations were made --- and that "
         r"is reported exactly in \Cref{sec:stats-workers}. Multiplying a job count by a guessed "
         "per-job token figure would produce a number with no evidentiary basis, so it is omitted "
         "rather than invented (\\textsc{claude.md} L0/L3: a number without a re-run command is not "
         "a finding).", "",
         r"\textbf{Other honest gaps.}",
         r"\begin{itemize}\setlength{\itemsep}{0.15ex}",
         r"\item The progenitor repository predates the \texttt{fr} controller, so it has no "
         "cycle/arm/outcome record at all. Its exploration history is reconstructible only from "
         r"%s work-log entries and %s commits, at coarser granularity than this repository's "
         r"%s controller cycles." % (num((p.get("worklog") or {}).get("entries")),
                                     num((p.get("git") or {}).get("commits")),
                                     num((s.get("frontier") or {}).get("max_cycle"))),
         r"\item The progenitor repository's issue tracker is stored in an embedded Dolt database "
         r"rather than an exported \texttt{issues.jsonl}, so its issue counts are not in this "
         "snapshot.",
         r"\item \texttt{fr} evidence records carry a self-reported \texttt{verdict} field whose "
         r"value is \texttt{claimed} on every one of the %s records that has one. It is a "
         "protocol marker, not an adjudication, and is therefore not tabulated as an outcome." %
         num(sum(((s.get("frontier") or {}).get("evidence_tiers") or {}).values())),
         r"\item Wave numbering (\texttt{W1}--\texttt{W%s}) is a human convention in the work log and "
         "wave documents; it is not a controller-enforced counter, and a few numbers were skipped or "
         "reused. Counts of wave \\emph{documents} are exact; the wave \\emph{index} is indicative." %
         tex((s.get("worklog") or {}).get("max_wave")),
         r"\item Cross-repository carry-over (what this campaign inherited from the progenitor) is "
         r"described qualitatively in \Cref{sec:stats-progenitor}; it is a judgement about content, "
         "not a count.",
         r"\end{itemize}", ""]
    return "\n".join(L)


def sec_calendar(data):
    s = data["successor"]
    p = data.get("progenitor") or {}
    sg, pg = s.get("git") or {}, p.get("git") or {}
    fr = s.get("frontier") or {}

    pts_prog = [(_dnum(d), n) for d, n in sorted((pg.get("per_day") or {}).items())]
    pts_succ = [(_dnum(d), n) for d, n in sorted((sg.get("per_day") or {}).items())]
    pts_fr = [(_dnum(d), n) for d, n in sorted((fr.get("per_day") or {}).items())]

    all_x = [x for x, _ in pts_prog + pts_succ + pts_fr]
    xmax = (max(all_x) + 2) if all_x else 1
    ticks, ticklabels = [], []
    d = 0
    while d <= xmax:
        day = CHART_ORIGIN + _dt.timedelta(days=d)
        ticks.append(str(d))
        ticklabels.append(day.strftime("%b %d"))
        d += 7

    chart = "\n".join([
        r"\begin{figure}[H]\centering",
        r"\begin{tikzpicture}",
        r"\begin{axis}[aismbase, ymajorgrids,",
        r"  xlabel={campaign day (day 0 $=$ %s, the progenitor's first commit)},"
        % tex(CHART_ORIGIN.isoformat()),
        r"  ylabel={events on that day},",
        r"  xmin=-1, xmax=%d, ymin=0," % xmax,
        r"  xtick={%s}, xticklabels={%s}," % (",".join(ticks), ",".join(ticklabels)),
        r"  xticklabel style={rotate=45, anchor=east},",
        r"  legend pos=north west, ybar, bar width=1.6pt,",
        r"]",
        r"\addplot[draw=oiBlue, fill=oiBlue] coordinates {%s};" % _coords(pts_prog),
        r"\addlegendentry{progenitor commits}",
        r"\addplot[draw=oiVermillion, fill=oiVermillion] coordinates {%s};" % _coords(pts_succ),
        r"\addlegendentry{this repository, commits}",
        r"\addplot[sharp plot, draw=oiGreen, mark=none, line width=0.9pt] coordinates {%s};"
        % _coords(pts_fr),
        r"\addlegendentry{\texttt{fr} controller cycles}",
        r"\end{axis}",
        r"\end{tikzpicture}",
        r"\caption{The campaign calendar. Bars are commits per calendar day in each repository; the "
        r"line is \texttt{fr} controller cycles per day in this repository. The three-week gap "
        r"between the two bar families is the interregnum between the progenitor's last commit "
        r"(%s) and this repository's stand-up (%s).}\label{fig:stats-calendar}"
        % (tex(pg.get("last_day")), tex(sg.get("first_day"))),
        r"\end{figure}",
    ])

    busiest = sorted((sg.get("per_day") or {}).items(), key=lambda kv: (-kv[1], kv[0]))[:5]
    rows = [" & ".join([tex(d), num(n),
                        num((fr.get("per_day") or {}).get(d, 0)),
                        num((fr.get("banked_per_day") or {}).get(d, 0)),
                        num((s.get("af") or {}).get("validation_days", {}).get(d, 0))])
            for d, n in busiest]

    L = [r"\subsection{The campaign calendar}\label{sec:stats-calendar}", "",
         "The two campaigns ran as short, dense bursts rather than as steady background work. "
         r"This repository put %s commits into %s calendar days with a commit (out of %s days "
         r"elapsed), and the progenitor put %s into %s."
         % (num(sg.get("commits")), num(sg.get("active_days")),
            num(_dnum(sg.get("last_day")) - _dnum(sg.get("first_day")) + 1
                if sg.get("first_day") else 0),
            num(pg.get("commits")), num(pg.get("active_days"))), "",
         chart, "",
         _table("l r r r r",
                r"Day & Commits & \texttt{fr} cycles & banked & \texttt{af} roots validated",
                rows,
                "The five heaviest days in this repository, by commit count.",
                "tab:stats-busiest",
                notes=r"``banked'' counts \texttt{fr} log records with outcome "
                      r"\texttt{banked}; the last column counts \texttt{af} proof trees whose root "
                      "node was validated that day."),
         ""]
    return "\n".join(L)


def sec_ladder(data):
    s = data["successor"]
    p = data.get("progenitor") or {}
    af, paf = s.get("af") or {}, p.get("af") or {}
    reg = s.get("registry") or {}
    dfs = s.get("definitions") or {}

    def cum(days):
        out, tot = [], 0
        for d in sorted(days):
            tot += days[d]
            out.append((_dnum(d), tot))
        return out

    c_succ = cum(af.get("validation_days") or {})
    c_prog = cum(paf.get("validation_days") or {})
    # extend each curve to the right edge so the step plot reads as a level, not a stop
    all_x = [x for x, _ in c_succ + c_prog]
    xmax = (max(all_x) + 2) if all_x else 1
    if c_prog:
        c_prog = c_prog + [(xmax, c_prog[-1][1])]
    if c_succ:
        c_succ = c_succ + [(xmax, c_succ[-1][1])]

    ticks, ticklabels = [], []
    d = 0
    while d <= xmax:
        ticks.append(str(d))
        ticklabels.append((CHART_ORIGIN + _dt.timedelta(days=d)).strftime("%b %d"))
        d += 7

    chart = "\n".join([
        r"\begin{figure}[H]\centering",
        r"\begin{tikzpicture}",
        r"\begin{axis}[aismbase, ymajorgrids,",
        r"  xlabel={campaign day (day 0 $=$ %s)}," % tex(CHART_ORIGIN.isoformat()),
        r"  ylabel={cumulative \texttt{af}-validated results},",
        r"  xmin=-1, xmax=%d, ymin=0," % xmax,
        r"  xtick={%s}, xticklabels={%s}," % (",".join(ticks), ",".join(ticklabels)),
        r"  xticklabel style={rotate=45, anchor=east},",
        r"  legend pos=north west,",
        r"]",
        r"\addplot[const plot, draw=oiBlue] coordinates {%s};" % _coords(c_prog),
        r"\addlegendentry{progenitor}",
        r"\addplot[const plot, draw=oiVermillion] coordinates {%s};" % _coords(c_succ),
        r"\addlegendentry{this repository}",
        r"\end{axis}",
        r"\end{tikzpicture}",
        r"\caption{The rigour ladder over time: cumulative count of proof trees whose root node "
        r"reached \texttt{validated} under the fresh-prover/fresh-verifier protocol. Each step is "
        r"one result crossing from \emph{claimed} to T0. Timestamps are read from the "
        r"\texttt{node\_validated} entries of the append-only \texttt{af} "
        r"ledgers.}\label{fig:stats-ladder}",
        r"\end{figure}",
    ])

    st = reg.get("status") or {}
    afc = reg.get("af") or {}
    total = reg.get("results") or 0
    st_rows = [" & ".join([code(k), num(v), pct(v, total)])
               for k, v in sorted(st.items(), key=lambda kv: (-kv[1], kv[0]))]
    af_rows = [" & ".join([code(k), num(v), pct(v, total)])
               for k, v in sorted(afc.items(), key=lambda kv: (-kv[1], kv[0]))]

    dk = dfs.get("kind") or {}
    ds = dfs.get("status") or {}
    def_rows = [" & ".join([code(k), num(v)]) for k, v in sorted(dk.items(), key=lambda kv: (-kv[1], kv[0]))]
    def_rows += [" & ".join([code("status: " + k), num(v)])
                 for k, v in sorted(ds.items(), key=lambda kv: (-kv[1], kv[0]))]

    L = [r"\subsection{The rigour ladder}\label{sec:stats-ladder}", "",
         r"The project's whole point is that a claim's \emph{status} is tracked honestly and "
         "separately from its plausibility. The registry therefore carries a status census, and "
         "the only rung that counts as rigorous in-repo is an "
         r"\texttt{af}-validated tree (or a byte-matched citation). Of %s registry results, "
         r"%s carry \texttt{af: validated} --- %s of the registry. The remainder are "
         "flagged non-rigorous in the open."
         % (num(total), num(afc.get("validated", 0)), pct(afc.get("validated", 0), total)), "",
         chart, "",
         _table("l r r", r"Registry \texttt{status:} & Results & Share", st_rows,
                "Status census of the result registry.", "tab:stats-status",
                notes=r"\texttt{proved} here means ``the shard's proof has been carried out and "
                      r"reviewed''; it becomes \emph{rigorous} only in combination with "
                      r"\texttt{af: validated} (next table). \texttt{proved-mod-audit} is the "
                      "inherited-campaign tag: a paper proof that has not cleared an independent "
                      "pass in this repository."),
         _table("l r r", r"\texttt{af:} field & Results & Share", af_rows,
                r"Formalisation state of the registry: how many results have an \texttt{af} "
                r"workspace, and how many reached a validated root.", "tab:stats-af",
                notes=r"\texttt{seeded} means a workspace exists with the registry contract as its "
                      "root conjecture but the tree is not (yet) closed."),
         _table("l r", "Definition shards & Count", def_rows,
                "The vocabulary layer: one definition per shard, provenance-gated.",
                "tab:stats-defs",
                notes=r"\texttt{cited} definitions byte-match a local source under \texttt{refs/}; "
                      r"\texttt{consensus} and \texttt{original} are adopted/introduced here and "
                      "lock only on recorded sign-off."),
         ""]
    return "\n".join(L)


def sec_arms(data):
    s = data["successor"]
    fr = s.get("frontier") or {}
    pf = s.get("portfolio") or {}
    arms = fr.get("arms") or {}
    ao = fr.get("arm_outcomes") or {}
    spans = fr.get("arm_span") or {}
    desc = {a["id"]: a for a in (pf.get("arms") or [])}

    ORDER = ["banked", "progress", "died", "refuted", "discovery", "orient"]
    keys = [k for k in ORDER if any(k in v for v in ao.values())]
    keys += sorted({k for v in ao.values() for k in v} - set(keys))

    arm_ids = sorted(arms, key=lambda a: (-arms[a], a))
    rows = []
    for a in arm_ids:
        cells = [code(a), num(arms[a])]
        for k in keys:
            cells.append(num(ao.get(a, {}).get(k, 0)))
        sp = spans.get(a) or {}
        cells.append(tex(_day(sp.get("first"))))
        cells.append(tex(_day(sp.get("last"))))
        cells.append(tex((desc.get(a) or {}).get("priority") or "--"))
        rows.append(" & ".join(cells))

    colspec = "l r " + "r " * len(keys) + "l l l"
    header = " & ".join([r"Arm", "Pulls"] + [code(k) for k in keys] +
                        ["First", "Last", "Priority now"])

    # stacked horizontal bars, one bar per arm
    plots = []
    palette = ["oiGreen", "oiBlue", "oiVermillion", "oiOrange", "oiPurple", "oiSky"]
    for i, k in enumerate(keys):
        pts = [(ao.get(a, {}).get(k, 0), a) for a in arm_ids]
        plots.append(r"\addplot[draw=%s, fill=%s] coordinates {%s}; \addlegendentry{%s}" % (
            palette[i % len(palette)], palette[i % len(palette)],
            " ".join("(%d,%s)" % (v, a) for v, a in pts), code(k)))

    chart = "\n".join([
        r"\begin{figure}[H]\centering",
        r"\begin{tikzpicture}",
        r"\begin{axis}[aismbase, height=5.6cm, xbar stacked, xmajorgrids,",
        r"  symbolic y coords={%s}, ytick=data," % ",".join(arm_ids),
        r"  xlabel={\texttt{fr} pulls on that arm}, xmin=0,",
        r"  bar width=8pt, legend style={at={(0.5,-0.28)}, anchor=north, legend columns=3},",
        r"  y dir=reverse,",
        r"]",
    ] + plots + [
        r"\end{axis}",
        r"\end{tikzpicture}",
        r"\caption{Attention allocation across research directions. Each bar is one \texttt{fr} "
        r"arm; segments are the recorded outcomes of the pulls on it. Records with no arm "
        r"(orientation and bookkeeping cycles) are excluded.}\label{fig:stats-arms}",
        r"\end{figure}",
    ])

    outc = fr.get("outcomes") or {}
    dec = fr.get("decisions") or {}
    tiers = fr.get("evidence_tiers") or {}
    narm = sum(arms.values())
    L = [r"\subsection{The exploration controller: arms and outcomes}\label{sec:stats-arms}", "",
         r"Research directions are registered as \texttt{fr} \emph{arms}; every harvested result is "
         r"logged as one pull with an outcome, and a Stop-hook circuit-breaker forces a stalled arm "
         r"to yield. Across %s cycles, %s carried an arm label and %s were orientation or "
         r"bookkeeping records. The controller recorded %s explicit allocation decisions: "
         "%s." % (num(fr.get("max_cycle") or fr.get("records")), num(narm),
                  num((fr.get("records") or 0) - narm), num(sum(dec.values())),
                  ", ".join("%s $\\times$ %s" % (code(k), num(v))
                            for k, v in sorted(dec.items(), key=lambda kv: (-kv[1], kv[0])))), "",
         chart, "",
         _longtable(colspec, header, rows,
                    "Per-arm ledger: pulls, outcomes, activity window, and current portfolio "
                    "priority.", "tab:stats-arms",
                    notes=r"Outcome vocabulary: \texttt{banked} = a result harvested and recorded; "
                          r"\texttt{progress} = movement without a bankable result; \texttt{died} / "
                          r"\texttt{refuted} = the direction was killed, with a certificate; "
                          r"\texttt{discovery} = an off-goal find routed to the portfolio.",
                    fontsize=r"\footnotesize"),
         "",
         "Aggregated over all cycles the outcome mix is %s. Evidence records are tiered %s."
         % (", ".join("%s~%s" % (num(v), code(k))
                      for k, v in sorted(outc.items(), key=lambda kv: (-kv[1], kv[0]))),
            ", ".join("%s~%s" % (num(v), code(k))
                      for k, v in sorted(tiers.items(), key=lambda kv: (-kv[1], kv[0])))),
         ""]
    return "\n".join(L)


def sec_elevations(data):
    s = data["successor"]
    af = s.get("af") or {}
    ws = [w for w in (af.get("workspaces_detail") or [])]
    val = [w for w in ws if w["root_validated"]]
    val.sort(key=lambda w: (w["root_validated"], w["id"]))

    rows = []
    for i, w in enumerate(val, 1):
        rows.append(" & ".join([
            num(i), code(w["id"]), num(w["nodes"]), num(w["validated"]),
            num(w["challenges"]), num(w["amendments"]), num(w["defs_imported"]),
            num(w["max_round"]), num(w["claims"]), tex(_day(w["root_validated"]))]))

    seeded = [w for w in ws if not w["root_validated"]]
    seeded.sort(key=lambda w: w["id"])

    nodes = sorted(w["nodes"] for w in ws)
    n = len(nodes)
    median = nodes[n // 2] if n % 2 else (nodes[n // 2 - 1] + nodes[n // 2]) / 2.0
    biggest = max(ws, key=lambda w: (w["nodes"], w["id"])) if ws else None
    most_ch = max(ws, key=lambda w: (w["challenges"], w["id"])) if ws else None
    most_rounds = max(ws, key=lambda w: (w["max_round"], w["id"])) if ws else None

    # histogram of tree sizes
    buckets = [(1, 5), (6, 10), (11, 15), (16, 20), (21, 30), (31, 40), (41, 60)]
    hist = []
    for lo, hi in buckets:
        hist.append(("%d--%d" % (lo, hi), sum(1 for w in ws if lo <= w["nodes"] <= hi)))
    chart = "\n".join([
        r"\begin{figure}[H]\centering",
        r"\begin{tikzpicture}",
        r"\begin{axis}[aismbase, height=5.2cm, ybar, ymajorgrids, bar width=16pt,",
        r"  symbolic x coords={%s}, xtick=data," % ",".join(b for b, _ in hist),
        r"  xlabel={nodes in the proof tree}, ylabel={workspaces}, ymin=0,",
        r"  nodes near coords, every node near coord/.append style={font=\scriptsize},",
        r"]",
        r"\addplot[draw=oiBlue, fill=oiBlue!70] coordinates {%s};" %
        " ".join("(%s,%d)" % (b, v) for b, v in hist),
        r"\end{axis}",
        r"\end{tikzpicture}",
        r"\caption{Size distribution of the %s adversarial proof trees. The median tree has %s "
        r"nodes; the largest, %s, has %s.}\label{fig:stats-treesize}"
        % (num(len(ws)), tex("%g" % median), code(biggest["id"]) if biggest else "--",
           num(biggest["nodes"]) if biggest else "--"),
        r"\end{figure}",
    ])

    et = af.get("entry_types") or {}
    et_rows = [" & ".join([code(k), num(v)])
               for k, v in sorted(et.items(), key=lambda kv: (-kv[1], kv[0]))]

    L = [r"\subsection{Adversarial elevations}\label{sec:stats-elevations}", "",
         "A result reaches the top in-repo rung only through an "
         r"\texttt{af} workspace: the registry contract becomes the root conjecture, a fresh prover "
         "agent builds a proof tree, and every node is validated by a \\emph{separate} fresh "
         "verifier told that finding a gap is a success. The orchestrator never judges a step. "
         r"%s workspaces were opened; %s reached a validated root and %s remain seeded or open. "
         r"Between them the workers built %s proof nodes, raised %s challenges (of which %s were "
         r"resolved), and forced %s node amendments."
         % (num(af.get("workspaces")), num(af.get("root_validated")),
            num(af.get("seeded_not_validated")), num(af.get("nodes_total")),
            num(af.get("challenges_total")),
            num((af.get("entry_types") or {}).get("challenge_resolved", 0)),
            num(af.get("amendments_total"))), "",
         chart, "",
         "The most-contested tree was %s (%s challenges raised); the longest-running was %s, which "
         "needed %s prover/verifier rounds before its root closed."
         % (code(most_ch["id"]) if most_ch else "--", num(most_ch["challenges"]) if most_ch else "--",
            code(most_rounds["id"]) if most_rounds else "--",
            num(most_rounds["max_round"]) if most_rounds else "--"), "",
         _table("l r", "Ledger entry type & Count", et_rows,
                r"The append-only \texttt{af} ledger, by entry type, summed over every workspace in "
                "this repository.", "tab:stats-ledger",
                notes=r"\texttt{nodes\_claimed} is the operational unit of work: one claim event is "
                      "one worker taking one node. It is the closest thing the record has to a job "
                      r"counter (\Cref{sec:stats-workers})."),
         "",
         _longtable(
             "r l r r r r r r r l",
             r"\# & Result & Nodes & Val. & Chal. & Amd. & Defs & Rnds & Jobs & Closed",
             rows,
             r"Every \texttt{af}-validated elevation in this repository, in the order its root node "
             "closed.",
             "tab:stats-elevations",
             notes="``Val.'' counts validated nodes; ``Chal.'' counts challenges raised by "
                   "verifiers against nodes of that tree; ``Amd.'' counts node statements the "
                   "prover had to change in response; ``Defs'' counts definitions imported into "
                   "the workspace as byte-matched externals; ``Rnds'' is the highest "
                   "prover/verifier round index reached; ``Jobs'' is the number of node-claim "
                   "events, i.e.\\ worker invocations against that tree; ``Closed'' is the day "
                   "the root node was validated. Fewer validated nodes than created nodes means "
                   "nodes were archived or superseded during the run.",
             fontsize=r"\footnotesize"),
         "",
         "The %s workspaces that were seeded but never closed a root are %s. A seeded-and-open "
         "workspace is a recorded state, not a failure: it means a contract exists and the tree is "
         "still being built or was superseded."
         % (num(len(seeded)), ", ".join(code(w["id"]) for w in seeded) or "none"),
         ""]
    return "\n".join(L)


def sec_workers(data):
    s = data["successor"]
    fr = s.get("frontier") or {}
    af = s.get("af") or {}
    p = data.get("progenitor") or {}
    paf = p.get("af") or {}

    w = fr.get("workers") or {}
    rows = [" & ".join([code(k.split(" / ")[0]), code(k.split(" / ")[1]), num(v)])
            for k, v in sorted(w.items(), key=lambda kv: (-kv[1], kv[0]))[:18]]
    other = sum(v for k, v in sorted(w.items(), key=lambda kv: (-kv[1], kv[0]))[18:])
    if other:
        rows.append(" & ".join([r"\multicolumn{2}{l}{\itshape %d further model/role pairs}"
                                % (len(w) - 18), num(other)]))

    orole = af.get("owner_roles") or {}
    or_rows = [" & ".join([code(k), num(v)])
               for k, v in sorted(orole.items(), key=lambda kv: (-kv[1], kv[0]))]

    total_claims = sum(orole.values())
    prog_claims = sum((paf.get("owner_roles") or {}).values())

    L = [r"\subsection{Worker and job census}\label{sec:stats-workers}", "",
         r"Two independent records count delegated work. The \texttt{fr} log names the workers "
         "involved in each harvested cycle as %s pairs; that is a curated, human-entered field "
         r"and covers %s worker mentions across %s distinct model/role pairs. The \texttt{af} "
         r"ledgers count \emph{invocations} mechanically: every \texttt{nodes\_claimed} entry is one "
         "worker taking one node, and the claim's owner string encodes whether it was the initial "
         "prover build, a prover fix round, or a verifier pass. That gives %s claim events in this "
         "repository and %s in the progenitor --- %s delegated adversarial jobs in total, each one "
         "a fresh model invocation."
         % (code("model:role"), num(fr.get("worker_jobs")), num(len(w)),
            num(total_claims), num(prog_claims), num(total_claims + prog_claims)), "",
         _table("l r", r"\texttt{af} claim owner & Claim events", or_rows,
                r"Mechanically counted \texttt{af} worker invocations in this repository, by role. "
                "Provers and verifiers are always separate fresh agents; the orchestrator never "
                "appears here because it never claims a node.", "tab:stats-afjobs"),
         _table("l l r", r"Model & Role & Cycles", rows,
                r"Worker mix as recorded in the \texttt{fr} controller log (curated field; one "
                "cycle may name several workers).", "tab:stats-workers",
                notes=r"\texttt{codex} entries are \texttt{gpt-5.6-sol} runs under the project's "
                      "model/effort policy; a few rows carry the fuller "
                      r"\texttt{codex-gpt-5.6-sol} spelling from before the label settled. "
                      r"\texttt{opus}, \texttt{sonnet}, and \texttt{fable} are Claude models acting "
                      "as orchestrator-side authors, strategists, and reviewers."),
         "",
         r"The progenitor's %s claim events are counted but not decomposed: that campaign predates "
         r"the \texttt{v-}/\texttt{pf-}/\texttt{prover-build} owner convention and used ad-hoc "
         r"worker names (\texttt{agent-A}, \texttt{prover-direct-sum}, \texttt{vtb-2.1}, \ldots), "
         "so only its total is comparable with the column above." % num(prog_claims), "",
         r"\textbf{What these numbers are not.} A claim event is a job, not a token budget. Job "
         "counts are exact and mechanically derived; token, cost, and wall-clock figures were never "
         r"recorded by either repository and are not estimated here (\Cref{sec:stats-method}).",
         ""]
    return "\n".join(L)


def sec_evidence(data):
    s = data["successor"]
    runs = s.get("runs") or {}
    docs = s.get("docs") or {}
    beads = s.get("beads") or {}
    refs = s.get("refs") or {}
    tool = s.get("tooling") or {}
    find = s.get("findings") or {}

    doc_rows = [
        (r"\texttt{docs/waves/} --- wave records", docs.get("waves")),
        (r"\texttt{docs/plans/} --- strategy and proof-sketch versions", docs.get("plans")),
        (r"\texttt{docs/audits/}, \texttt{lit-review/}, \texttt{recon/}, "
         r"\texttt{tooling-feedback/}",
         (docs.get("audits", 0) + docs.get("lit-review", 0) + docs.get("recon", 0) +
          docs.get("tooling-feedback", 0))),
        (r"\texttt{docs/ingest/} --- the inherited classical portfolio",
         docs.get("ingest")),
        (r"\quad of which experiment files", docs.get("ingest_experiment_files")),
        (r"\texttt{runs/} --- numerical run bundles", runs.get("bundles")),
        (r"\quad producing scripts inside bundles", runs.get("bundle_scripts")),
        (r"\texttt{report/sections/} --- lab-book shards", docs.get("report_shards")),
        (r"\quad lines of \LaTeX{} in them", docs.get("report_shard_lines")),
        (r"\texttt{refs/} --- pinned ground-truth sources", refs.get("sources")),
        (r"\texttt{scripts/} --- tooling files", tool.get("script_files")),
        (r"\quad lines of tooling code", tool.get("script_lines")),
        (r"\quad of which validation gates", tool.get("gate_scripts")),
        (r"\quad lines in the gates", tool.get("gate_lines")),
        (r"\quad gate unit-test files / lines",
         None),
    ]
    rows = []
    for label, v in doc_rows:
        if v is None:
            rows.append(" & ".join([label, "%s / %s" % (num(tool.get("test_files")),
                                                        num(tool.get("test_lines")))]))
        else:
            rows.append(" & ".join([label, num(v)]))

    fb = beads.get("status") or {}
    b_rows = [" & ".join([code(k), num(v)]) for k, v in sorted(fb.items(), key=lambda kv: (-kv[1], kv[0]))]

    tags = find.get("mechanism_tags") or {}
    t_rows = [" & ".join([code(k), num(v)]) for k, v in sorted(tags.items())]

    L = [r"\subsection{Evidence, artifacts, and dead routes}\label{sec:stats-evidence}", "",
         "Numerical work is quarantined by construction: every experiment is a run bundle with a "
         "re-run command, a schema, an index row, and a checkable invariant, and is never rigorous. "
         r"%s such bundles exist. The inherited campaign record (\texttt{docs/ingest/}) carries a "
         "further %s experiment files, including the 67{,}000-instance exact enumeration that "
         "supports the linear law and the (EX) conjecture --- evidence, and proof of nothing."
         % (num(runs.get("bundles")), num(docs.get("ingest_experiment_files"))), "",
         _table("l r", "Artifact class & Count", rows,
                "Document and tooling production in this repository.", "tab:stats-artifacts"),
         "",
         "The negative record is kept as deliberately as the positive one. "
         r"\texttt{FINDINGS.md} carries %s dated entries with %s explicit "
         r"do-not-re-walk markers, indexed by mechanism; \texttt{docs/LEARNINGS.md} records %s "
         "retracted in-repo claims (a retraction is a success of the machinery, not an "
         "embarrassment)."
         % (num(find.get("dated_entries")), num(find.get("stop_markers")),
            num(find.get("retractions"))), "",
         _table("l r", "Mechanism tag in the findings index & Entries", t_rows,
                r"The dead-route census, read off the hand-built mechanism index in "
                r"\texttt{FINDINGS.md}.", "tab:stats-deadroutes",
                notes=r"\textsc{dead-route} is a permanent kill with a certificate; \textsc{wall} is "
                      r"a structural limit found, not a route kill; \textsc{retired-route} is "
                      "superseded rather than refuted. The distinction is load-bearing: only the "
                      "first forbids re-walking."),
         _table("l r", "Issue status & Count", b_rows,
                "The issue tracker at the snapshot instant (%s issues plus %s persistent memory "
                "records)." % (num(beads.get("issues")), num(beads.get("memories"))),
                "tab:stats-issues"),
         ""]
    return "\n".join(L)


def sec_progenitor(data):
    s = data["successor"]
    p = data.get("progenitor") or {}
    if not p:
        return (r"\subsection{Progenitor}\label{sec:stats-progenitor}" "\n\n"
                "No progenitor snapshot is present in the extract.\n")
    pg, sg = p.get("git") or {}, s.get("git") or {}
    paf, af = p.get("af") or {}, s.get("af") or {}
    preg, reg = p.get("registry") or {}, s.get("registry") or {}
    carried = p.get("carried_forward")

    L = [r"\subsection{Progenitor and successor}\label{sec:stats-progenitor}", "",
         "The classical portfolio was not born here. It began as a side-quest inside "
         "%s, whose own target was the non-commutative "
         % code_brk("almost-idempotent-positive-maps") +
         "problem; the classical case was its proving ground. That campaign ran %s to %s "
         "(%s commits, %s work-log entries) and reached %s registry results with %s "
         r"\texttt{af}-validated roots across %s workspaces and %s proof nodes. This repository "
         "was stood up %s --- %s days later --- specifically to re-establish the classical result "
         "from scratch under a stricter ladder."
         % (tex(pg.get("first_day")), tex(pg.get("last_day")), num(pg.get("commits")),
            num((p.get("worklog") or {}).get("entries")), num(preg.get("results")),
            num(paf.get("root_validated")), num(paf.get("workspaces")), num(paf.get("nodes_total")),
            tex(sg.get("first_day")),
            num(_dnum(sg["first_day"]) - _dnum(pg["last_day"])
                if sg.get("first_day") and pg.get("last_day") else 0)), "",
         r"\textbf{What carried over.} Three things, and each was re-tagged \emph{down} on arrival:",
         r"\begin{itemize}\setlength{\itemsep}{0.15ex}",
         r"\item \textbf{The reduction chain.} The progenitor reduced the classical stability "
         "statement, through audited and audit-pending steps, to a single open kernel (the "
         r"``(EX)'' conjecture). The chain re-entered this repository as \texttt{stated} or "
         r"\texttt{proved-mod-audit} --- objects of study, not oracles --- and %s of the %s "
         "registry results here still carry that inherited tag."
         % (num((reg.get("status") or {}).get("proved-mod-audit", 0)), num(reg.get("results"))),
         r"\item \textbf{The numerical record.} The 67{,}000-instance exact enumeration and the "
         "seed experiments were copied wholesale into "
         r"\texttt{docs/ingest/} (%s files) and re-homed as run bundles. Their status did not "
         r"change: \texttt{numerical}, L3, never rigorous."
         % num((s.get("docs") or {}).get("ingest_experiment_files")),
         r"\item \textbf{One validated result.} Exactly one classical result had cleared an "
         r"\texttt{af} validation upstream --- \texttt{lem-classical-equiv}, the "
         r"signed$\leftrightarrow$stochastic bridge. It was nevertheless re-validated here from "
         r"scratch (%s nodes, %s challenges) and that in-repo run, not the upstream one, is what "
         "this repository's ladder rests on."
         % (num(next((w["nodes"] for w in (af.get("workspaces_detail") or [])
                      if w["id"] == "lem-classical-equiv"), None)),
            num(next((w["challenges"] for w in (af.get("workspaces_detail") or [])
                      if w["id"] == "lem-classical-equiv"), None))),
         r"\end{itemize}", "",
         "In throughput terms the successor is roughly %s times the progenitor in commits, %s "
         r"times in registry size, and %s times in \texttt{af}-validated results, over %s times "
         "the elapsed span."
         % (tex("%.1f" % ((sg.get("commits") or 0) / max(1, pg.get("commits") or 1))),
            tex("%.1f" % ((reg.get("results") or 0) / max(1, preg.get("results") or 1))),
            tex("%.1f" % ((af.get("root_validated") or 0) / max(1, paf.get("root_validated") or 1))),
            tex("%.1f" % (((_dnum(sg["last_day"]) - _dnum(sg["first_day"]) + 1) /
                           max(1.0, _dnum(pg["last_day"]) - _dnum(pg["first_day"]) + 1))
                          if all((sg.get("first_day"), sg.get("last_day"),
                                  pg.get("first_day"), pg.get("last_day"))) else 0))),
         ""]
    if carried:
        L += [r"\emph{Note.} The progenitor block of this snapshot was carried forward from a "
              "previous extraction: the sibling repository was not present on the machine that last "
              "refreshed the data.", ""]
    return "\n".join(L)


def sec_colophon(data):
    s = data["successor"]
    p = data.get("progenitor") or {}
    L = [r"\subsection{Colophon: how this section stays true}\label{sec:stats-colophon}", "",
         r"Everything in \Cref{sec:campaign-statistics} is generated by "
         r"\texttt{scripts/gen-report-stats.py} into \texttt{report/generated/stats/}. The shard in "
         r"\texttt{report/sections/} contains no numbers; it only \texttt{\textbackslash input}s the "
         "generated body.", "",
         r"\textbf{The staleness problem.} Statistics about a repository depend on things that "
         "change with every commit --- git history, the controller log, the proof ledgers. A "
         "byte-for-byte freshness gate over such a generator would be permanently red, because the "
         "very commit that lands the regenerated tables changes their inputs again. The generator "
         "therefore runs in two halves with a committed snapshot between them:", "",
         r"\begin{quote}\footnotesize\raggedright",
         r"\texttt{python3 scripts/gen-report-stats.py --extract}\par",
         r"\hspace*{1.5em}mines the live sources into "
         r"\texttt{report/generated/stats/campaign-extract.json} \emph{and} re-renders."
         r"\par\smallskip",
         r"\texttt{python3 scripts/gen-report-stats.py}\par",
         r"\hspace*{1.5em}renders the \texttt{.tex} files from that committed snapshot, "
         r"deterministically.\par\smallskip",
         r"\texttt{python3 scripts/gen-report-stats.py --check}\par",
         r"\hspace*{1.5em}the gate: re-renders, byte-compares, and prints a non-fatal drift "
         r"advisory.",
         r"\end{quote}", "",
         r"\textbf{Staleness semantics.} Only the render step is gated, so the check is stable "
         "across ordinary commits and fails exactly when it should: a hand-edited generated file, "
         "or a renderer change without a re-render. The \\emph{numbers}, by contrast, are as of "
         r"\textbf{%s} and go stale silently by design --- refreshing them is a deliberate act. "
         r"\texttt{--check} therefore also compares a few cheap live counts against the snapshot and "
         "prints how far behind it is, without blocking a commit."
         % tex(data.get("extracted_at")), "",
         r"\textbf{Progenitor data.} The %s block is mined "
         "live when that repository sits beside this one and is otherwise carried forward from the "
         % code_brk("almost-idempotent-positive-maps") +
         "committed snapshot, so the gate is green on machines that do not have the sibling. The "
         "current block was mined %s."
         % ("live at the last extraction" if not p.get("carried_forward")
            else "on an earlier machine and carried forward"), "",
         r"\textbf{Provenance of the figures.} %s controller records, %s \texttt{af} ledger "
         "entries, %s registry shards, %s definition shards, %s run bundles, %s work-log entries, "
         "%s issue records, and %s commits were read to produce this section."
         % (num((s.get("frontier") or {}).get("records")),
            num((s.get("af") or {}).get("ledger_entries")),
            num((s.get("registry") or {}).get("results")),
            num((s.get("definitions") or {}).get("definitions")),
            num((s.get("runs") or {}).get("bundles")),
            num((s.get("worklog") or {}).get("entries")),
            num((s.get("beads") or {}).get("issues")),
            num(((s.get("git") or {}).get("commits") or 0) +
                ((p.get("git") or {}).get("commits") or 0))),
         ""]
    return "\n".join(L)


def render_body(data):
    parts = [BANNER,
             "% Body of the campaign-statistics section. Rendered from campaign-extract.json.",
             "% The shard report/sections/NN_campaign_statistics.tex \\input{}s this file.",
             "",
             "% This section is dense in unhyphenatable \\texttt{} identifiers. \\emergencystretch",
             "% lets TeX loosen a line as a LAST resort rather than run into the margin; it is",
             "% restored at the end of the section so no other shard is affected.",
             r"\emergencystretch=6em\relax", "",
             sec_headline(data), "",
             sec_method(data), "",
             sec_calendar(data), "",
             sec_ladder(data), "",
             sec_arms(data), "",
             sec_elevations(data), "",
             sec_workers(data), "",
             sec_evidence(data), "",
             sec_progenitor(data), "",
             sec_colophon(data), "",
             r"\emergencystretch=0pt\relax"]
    return "\n".join(parts).rstrip() + "\n"


# ======================================================================= main

def _write(files):
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, text in sorted(files.items()):
        (OUT_DIR / name).write_text(text, encoding="utf-8")


def _drift_advisory(data):
    """Cheap live-vs-snapshot comparison. Advisory only — never fails the gate."""
    snap = data.get("successor") or {}
    msgs = []
    live_fr = extract_frontier(ROOT) or {}
    if live_fr.get("records") is not None:
        d = live_fr["records"] - ((snap.get("frontier") or {}).get("records") or 0)
        if d:
            msgs.append("fr log %+d records" % d)
    live_reg = extract_registry(ROOT) or {}
    if live_reg.get("results") is not None:
        d = live_reg["results"] - ((snap.get("registry") or {}).get("results") or 0)
        if d:
            msgs.append("registry %+d results" % d)
    live_af = extract_af(ROOT) or {}
    if live_af.get("root_validated") is not None:
        d = live_af["root_validated"] - ((snap.get("af") or {}).get("root_validated") or 0)
        if d:
            msgs.append("af roots %+d" % d)
    return msgs


def main(argv):
    args = set(argv[1:])
    unknown = args - {"--extract", "--check", "--render"}
    if unknown:
        sys.stderr.write("unknown argument(s): %s\n" % ", ".join(sorted(unknown)))
        return 2

    if "--extract" in args:
        data = do_extract()
        _write(render(data))
        print("[gen-report-stats] extracted %s and rendered %d files into %s"
              % (data["extracted_at"], len(GENERATED_TEX), OUT_DIR.relative_to(ROOT)))
        return 0

    if not EXTRACT.is_file():
        sys.stderr.write("[gen-report-stats] missing %s — run with --extract first\n"
                         % EXTRACT.relative_to(ROOT))
        return 1
    data = json.loads(_read(EXTRACT))
    files = render(data)

    if "--check" in args:
        bad = []
        for name, text in sorted(files.items()):
            path = OUT_DIR / name
            if not path.is_file():
                bad.append("%s: MISSING" % name)
            elif path.read_text(encoding="utf-8") != text:
                bad.append("%s: STALE (regenerate with python3 scripts/gen-report-stats.py)" % name)
        for m in _drift_advisory(data):
            print("[gen-report-stats] drift advisory (not an error): snapshot is behind — %s" % m)
        if bad:
            for b in bad:
                sys.stderr.write("[gen-report-stats] %s\n" % b)
            return 1
        print("[gen-report-stats] OK — %d generated files match the committed snapshot (%s)"
              % (len(files), data.get("extracted_at")))
        return 0

    _write(files)
    print("[gen-report-stats] rendered %d files from snapshot %s"
          % (len(files), data.get("extracted_at")))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
